import {createRegistrationPopup} from '../components/merchantRegister.js'

document.addEventListener("DOMContentLoaded",()=>{
    const reservationBtn = document.querySelector(".reservation-btn")
    reservationBtn.parentElement.removeChild(reservationBtn)
    
    //load edit icons
    loadEditableFields()
    document.getElementById("app").append(createRegistrationPopup())
})

function loadEditableFields(){
    const editButton = document.createElement('button')
    editButton.innerText = "Edit Details"
    editButton.classList.add("edit-btn","btn")

    const restaurant_header = document.querySelector("#restaurant-name")
    restaurant_header.append(editButton);

    editButton.addEventListener("click",()=>{
        document.querySelector('body').appendChild(createEditPopup())
    })



    
}



function createEditPopup() {
  // Main popup container
  const popup = document.createElement('div');
  popup.id = 'edit-Popup';
  popup.classList.add('popup');

  // Popup content
  const content = document.createElement('div');
  content.classList.add('popup-content');

  // Close button
  const closeBtn = document.createElement('button');
  closeBtn.classList.add('close-btn');
  closeBtn.id = 'closeSignup';
  closeBtn.innerHTML = '&times;';

  closeBtn.addEventListener("click", ()=>{
    popup.parentElement.removeChild(popup)
  })

  // Header
  const heading = document.createElement('h2');
  heading.textContent = 'Edit Restaurant Details';

  // Form
  const form = document.createElement('form');
  form.id = 'edit-form';

  // Input: Restaurant Name
  const nameInput = document.createElement('input');
  nameInput.type = 'text';
  nameInput.id = 'rest-name';
  nameInput.placeholder = 'Restaurant Name';
  nameInput.required = 'true'


  // Input: Tags
  const tagsInput = document.createElement('input');
  tagsInput.type = 'text';
  tagsInput.id = 'rest-tags';
  tagsInput.placeholder = 'tags, separated, by commas';
  tagsInput.required = true
  tagsInput.minLength = 3

  // Input: Location
  const locationInput = document.createElement('input');
  locationInput.type = 'text';
  locationInput.id = 'rest-location';
  locationInput.placeholder = "123 Main St, Toronto, Canada";
  locationInput.required = true;
  locationInput.minLength = 10;
  locationInput.pattern = '^\\d+[\\w\\s]*,\\s*[\\w\\s]+,\\s*[\\w\\s]+$'; //generated by Grok
  locationInput.title = "Enter an address like '123 Main St, Toronto, Canada' with at least one number in the street, followed by two commas separating street, city, and country/province.";

  // Save Button
  const saveBtn = document.createElement('button');
  saveBtn.type = 'submit';
  saveBtn.classList.add('save-btn', 'btn');
  saveBtn.textContent = 'Save Changes';

  // Build form
  form.append(nameInput, tagsInput, locationInput, saveBtn);

  // Assemble popup
  content.append(closeBtn, heading, form);
  popup.appendChild(content);

  saveEditChanges(saveBtn,form,nameInput,tagsInput,locationInput,popup)
  // Return the full popup element

  return popup;
}

function saveEditChanges(save_button,form,input_name, input_tags, input_location, popup){
    const rest_name = document.querySelector("#restaurant-name>h1");
    const tags = document.querySelector(".tags")
    const location = document.querySelector("#restaurant-location>span")

    input_name.value = rest_name.innerText

    var old_tags = [...tags.querySelectorAll('p')]
                    .map(tag=> `${tag.innerText},`).join('')
    input_tags.value = old_tags.slice(0,-1)

    input_location.value = location.innerText;

    form.addEventListener('submit',(e)=>{
        e.preventDefault()

        if(form.checkValidity()){
        const new_tags = input_tags.value.split(',').filter(tag => tag.length>2)

        //make request to back end

        //upon success
        rest_name.innerText = input_name.value //set the new restaurant name
        location.innerText = input_location.value //set new location
        tags.innerHTML = new_tags.map(tag => `<p>${tag}</p>`).join('');
        popup.parentElement.removeChild(popup)
        }
    });

}
