import { goToLogin } from "./nav.js";
import {api} from "../global.js"
import { display_popup_msg } from "./popupMsg.js"; 
import { getUserState,setUserState } from "../utils.js";
import { formatPhoneNumber } from "../logic/format-utils.js";

export function createRegistrationPopup() {
  // Main popup container
  const popup = document.createElement('div');
  popup.classList.add('popup');

  // Popup content
  const content = document.createElement('div');
  content.classList.add('popup-content');

  // Close button
  const closeBtn = document.createElement('button');
  closeBtn.classList.add('close-btn');
  closeBtn.id = 'closeSignup';
  closeBtn.innerHTML = '&times;';

  closeBtn.addEventListener("click", ()=>{
    popup.parentElement.removeChild(popup)
  })

  // Header
  const heading = document.createElement('h2');
  heading.textContent = 'Restaurant Registration';

  // Form
  const form = document.createElement('form');
  form.id = 'edit-form';

  // Input: Restaurant Name
  const nameInput = document.createElement('input');
  nameInput.type = 'text';
  nameInput.id = 'rest-name';
  nameInput.placeholder = 'Restaurant Name';
  nameInput.required = 'true'

  // Input: Tags
  const tagsInput = document.createElement('input');
  tagsInput.type = 'text';
  tagsInput.id = 'rest-tags';
  tagsInput.placeholder = 'Tags: create tags, separated, by commas';
  tagsInput.required = true
  tagsInput.minLength = 3

  // Input: Location
  const locationInput = document.createElement('input');
  locationInput.type = 'text';
  locationInput.id = 'rest-location';
  locationInput.placeholder = "Address: 123 Main St, Toronto, Canada";
  locationInput.required = true;
  locationInput.minLength = 10;
  locationInput.pattern = '^\\d+[\\w\\s]*,\\s*[\\w\\s]+,\\s*[\\w\\s]+$'; //generated by Grok
  locationInput.title = "Enter an address like '123 Main St, Toronto, Canada' with at least one number in the street, followed by two commas separating street, city, and country/province.";

  // Input: Phone number
  const phoneInput = document.createElement('input');
  phoneInput.type = 'tel';
  phoneInput.id = 'rest-phone';
  phoneInput.placeholder = "Phone: (XXX) XXX-XXXX";
  phoneInput.required = true;
  phoneInput.pattern = "^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$" // "^[+]?[\\s\\-\\(\\)0-9]{10,20}$"; //generated by Grok
  phoneInput.title = "Enter a valid phone number: (XXX) XXX-XXXX";
  phoneInput.addEventListener('input',()=>
    {phoneInput.value= formatPhoneNumber(phoneInput.value)});


  // Register Button
  const registerBtn = document.createElement('button');
  registerBtn.type = 'submit';
  registerBtn.classList.add('register-btn', 'btn');
  registerBtn.textContent = 'Register';

  // Build form
  form.append(nameInput, tagsInput, phoneInput, locationInput, registerBtn);

  // Assemble popup
  content.append(closeBtn, heading, form);
  popup.appendChild(content);

  completeRegistration(form,nameInput,tagsInput,phoneInput,locationInput,popup)
  // Return the full popup element

  const app = document.getElementById('app');
  if(!getUserState())
    display_popup_msg("Requirement", 
      "You need to be logged-in or be a registered user to become a merchant", goToLogin)
  else
    app.append(popup);
}

function completeRegistration(form,input_name, input_tags, input_phone,input_location, popup){

    form.addEventListener('submit',async (e)=>{
        e.preventDefault()
        const user = getUserState();

        if(form.checkValidity()){
        const new_tags = input_tags.value.split(',').filter(tag => tag.trim().length>2) //clean up tags input into an array of tags
        const res = await api.createRestaurant(user.userID,input_name.value, new_tags,
        input_location.value,input_phone.value)

        if(res.code<300){
          alert("New Restaurant Creation successfull")
          user.restID = res.restID
          setUserState(user)
          window.location.reload();
        }else{
          alert(`code: ${res.code} ::: ${res.message}`)
          popup.parentElement.removeChild(popup)
        }
      }

    });

}