import {phone_num_strip, phone_num_validator} from '../logic/validators.js'

export function createRegistrationPopup() {
  // Main popup container
  const popup = document.createElement('div');
  popup.id = 'edit-Popup';
  popup.classList.add('popup');

  // Popup content
  const content = document.createElement('div');
  content.classList.add('popup-content');

  // Close button
  const closeBtn = document.createElement('button');
  closeBtn.classList.add('close-btn');
  closeBtn.id = 'closeSignup';
  closeBtn.innerHTML = '&times;';

  closeBtn.addEventListener("click", ()=>{
    popup.parentElement.removeChild(popup)
  })

  // Header
  const heading = document.createElement('h2');
  heading.textContent = 'Restaurant Registration';

  // Form
  const form = document.createElement('form');
  form.id = 'edit-form';

  // Input: Restaurant Name
  const nameInput = document.createElement('input');
  nameInput.type = 'text';
  nameInput.id = 'rest-name';
  nameInput.placeholder = 'Restaurant Name';
  nameInput.required = 'true'

  // Input: Tags
  const tagsInput = document.createElement('input');
  tagsInput.type = 'text';
  tagsInput.id = 'rest-tags';
  tagsInput.placeholder = 'Tags: create tags, separated, by commas';
  tagsInput.required = true
  tagsInput.minLength = 3

  // Input: Location
  const locationInput = document.createElement('input');
  locationInput.type = 'text';
  locationInput.id = 'rest-location';
  locationInput.placeholder = "Address: 123 Main St, Toronto, Canada";
  locationInput.required = true;
  locationInput.minLength = 10;
  locationInput.pattern = '^\\d+[\\w\\s]*,\\s*[\\w\\s]+,\\s*[\\w\\s]+$'; //generated by Grok
  locationInput.title = "Enter an address like '123 Main St, Toronto, Canada' with at least one number in the street, followed by two commas separating street, city, and country/province.";

  // Input: Phone number
  const phoneInput = document.createElement('input');
  phoneInput.type = 'tel';
  phoneInput.id = 'rest-phone';
  phoneInput.placeholder = "Phone: +1 204 123 1234";
  phoneInput.required = true;
  phoneInput.title = "Enter a valid phone number (10–15 digits)";
  phoneInput.minLength = 10
  phoneInput.maxLength = 15
  phoneInput.addEventListener('input', (e) => {
  e.target.value = phone_num_strip(e.target.value)
 });

  // Save Button
  const registerBtn = document.createElement('button');
  registerBtn.type = 'submit';
  registerBtn.classList.add('register-btn', 'btn');
  registerBtn.textContent = 'Register';

  // Build form
  form.append(nameInput, tagsInput, phoneInput, locationInput, registerBtn);

  // Assemble popup
  content.append(closeBtn, heading, form);
  popup.appendChild(content);

  completeRegistration(registerBtn,form,nameInput,tagsInput,phoneInput,locationInput,popup)
  // Return the full popup element

  return popup;
}

function completeRegistration(register_button,form,input_name, input_tags, input_phone,input_location, popup){
    const rest_name = document.querySelector("#restaurant-name>h1");
    const tags = document.querySelector(".tags")
    const location = document.querySelector("#restaurant-location>span")




    form.addEventListener('submit',(e)=>{
        e.preventDefault()

        if(form.checkValidity()){
        const new_tags = input_tags.value.split(',').filter(tag => tag.length>2)

        //make request to back end

        //upon success
        rest_name.innerText = input_name.value //set the new restaurant name
        location.innerText = input_location.value //set new location
        tags.innerHTML = new_tags.map(tag => `<p>${tag}</p>`).join('');
        popup.parentElement.removeChild(popup)
        }
    });

}