name: Linter

on: [push, pull_request]

jobs:
    build:
        name: Linting Code
        runs-on: ubuntu-latest

        permissions:
          contents: read
          packages: read
          statuses: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
        
            - name: Run Super-Linter
              uses: super-linter/super-linter@v8.2.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

                # Validate changed files
                VALIDATE_ALL_CODEBASE: false

                # Detailed error messages
                LOG_LEVEL: WARN

                # Languages to validate
                VALIDATE_JAVASCRIPT_ES: true
                VALIDATE_TYPESCRIPT_ES: true